application: estate-proto
version: 1
api_version: 1
runtime: python

default_expiration: "1d"

handlers:

- url: /css
  static_dir: assets/css
  secure: optional

- url: /js
  static_dir: assets/js
  secure: optional

- url: /img
  static_dir: assets/img
  secure: optional

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  secure: optional

- url: /admin.*
  script: main.py
  login: required
  secure: optional

- url: /oid/.*
  script: main.py
  secure: optional

- url: /contact/.*
  script: main.py
  secure: always

- url: /logout
  script: main.py

- url: .*
  script: main.py
  login: required
  secure: optional
