#!-*- coding:utf-8 -*-
from model.prefecture import Prefecture

p = Prefecture.all()

if p.count() == 0:
  Prefecture(code='01',name=u'北海道').put()
  Prefecture(code='02',name=u'青森県').put()
  Prefecture(code='03',name=u'岩手県').put()
  Prefecture(code='04',name=u'宮城県').put()
  Prefecture(code='05',name=u'秋田県').put()
  Prefecture(code='06',name=u'山形県').put()
  Prefecture(code='07',name=u'福島県').put()
  Prefecture(code='08',name=u'茨城県').put()
  Prefecture(code='09',name=u'栃木県').put()
  Prefecture(code='10',name=u'群馬県').put()
  Prefecture(code='11',name=u'埼玉県').put()
  Prefecture(code='12',name=u'千葉県').put()
  Prefecture(code='13',name=u'東京都').put()
  Prefecture(code='14',name=u'神奈川県').put()
  Prefecture(code='15',name=u'新潟県').put()
  Prefecture(code='16',name=u'富山県').put()
  Prefecture(code='17',name=u'石川県').put()
  Prefecture(code='18',name=u'福井県').put()
  Prefecture(code='19',name=u'山梨県').put()
  Prefecture(code='20',name=u'長野県').put()
  Prefecture(code='21',name=u'岐阜県').put()
  Prefecture(code='22',name=u'静岡県').put()
  Prefecture(code='23',name=u'愛知県').put()
  Prefecture(code='24',name=u'三重県').put()
  Prefecture(code='25',name=u'滋賀県').put()
  Prefecture(code='26',name=u'京都府').put()
  Prefecture(code='27',name=u'大阪府').put()
  Prefecture(code='28',name=u'兵庫県').put()
  Prefecture(code='29',name=u'奈良県').put()
  Prefecture(code='30',name=u'和歌山県').put()
  Prefecture(code='31',name=u'鳥取県').put()
  Prefecture(code='32',name=u'島根県').put()
  Prefecture(code='33',name=u'岡山県').put()
  Prefecture(code='34',name=u'広島県').put()
  Prefecture(code='35',name=u'山口県').put()
  Prefecture(code='36',name=u'徳島県').put()
  Prefecture(code='37',name=u'香川県').put()
  Prefecture(code='38',name=u'愛媛県').put()
  Prefecture(code='39',name=u'高知県').put()
  Prefecture(code='40',name=u'福岡県').put()
  Prefecture(code='41',name=u'佐賀県').put()
  Prefecture(code='42',name=u'長崎県').put()
  Prefecture(code='43',name=u'熊本県').put()
  Prefecture(code='44',name=u'大分県').put()
  Prefecture(code='45',name=u'宮崎県').put()
  Prefecture(code='46',name=u'鹿児島県').put()
  Prefecture(code='47',name=u'沖縄県').put()
